### ISSUE TITLE
dynamic class loaded

### ISSUE THREAD

**Issue by IvanKhulap** [nccgroup/house#13]
Does not work with dynamic loaded classes

**Comment by H4oK3** [comment]
Unfortunately it does not support that yet, as a matter of fact doing that using Frida maybe tricky; the Frida API involved in House works like this: it will do an enumerate against the dex file to resolve the symbols; if it is dynamically loaded, it cannot identify those. I am going to close this for now as this is one of the edge case and if I were you I would just look around for frida API to achieve that.

**Comment by IvanKhulap** [comment]
Dynamically loaded classes can be seen in enumAllClasses () 
For use dynamically loaded class ...
```
Java.perform(function(){
        var hookClass = undefined;
        var ClassUse = Java.use("java.lang.Class");
        var dexclassLoader = Java.use("dalvik.system.DexClassLoader");
         dexclassLoader.loadClass.overload('java.lang.String').implementation = function(name){
            var hookname = "com.dynamic.class.loaded";
            var result = this.loadClass(name,false);
             if(name == hookname){
                var hookClass = result;
                var hookClassCast = Java.cast(hookClass,ClassUse);
                 var methods = hookClassCast.getDeclaredMethods();
				console.log(methods);
                return result;
             }
            return result;
        }
});
```

**Comment by H4oK3** [comment]
Hey this looks nifty; I am reopening it and I will take a look at it when I get the chance; currently I am afraid I do not have much energy to spare on House due to some personal issues; I think it would not be to challenging if your script works; do you mind try to file a PR with that script added as a template script in House?

**Comment by H4oK3** [comment]
Also would you mind let me know your email address? In case I might need to ask sth from you when I work on it.

**Comment by H4oK3** [comment]
Feature added in the new updates
