### ISSUE TITLE
Monitor HTTP request/response body

### ISSUE THREAD

**Issue by Tyilo** [nccgroup/house#18]
Would it be possible to extend house to also include HTTP request/response bodies?

**Comment by H4oK3** [comment]
Currently I am not quite into implementing it, sure it can be done by hooking certain functions but in my mobile testing gigs I usually just use burp or wireshark; I think that would be more reliable and more efficient.

**Comment by Tyilo** [comment]
I see, however the SSL unpinning doesn't always seem to work (it crashed an app I tested)

**Comment by H4oK3** [comment]
ah that sounds an issue to me, ssl unpinning currently does not support **all** pinning libs, it might not work sometimes but I don't know why it would crash your app lol
