### ISSUE TITLE
SSL Pinning Not Work

### ISSUE THREAD

**Issue by hadi500** [nccgroup/house#27]
hi, house can't bypass SSL Pinning for : 
https://play.google.com/store/apps/details?id=com.bpm.sekeh&hl=fa
not work, can you check that ?

**Comment by empty-jack** [comment]
Hi, the framework using that frida script: https://codeshare.frida.re/@masbog/frida-android-unpinning-ssl/
It isn't universal method, check application's ssl verifier class. Just find keywords in app's code like: 'sslTrust', 'sslCert', 'x509', etc... and write your own script.

**Comment by H4oK3** [comment]
what @empty-jack said is correct, @hadi500 if possible please reverse the APK a bit yourself and let me know which SSL lib is being used and I will update House to support cert unpinning on that lib
