### ISSUE TITLE
App shelling?

### ISSUE THREAD

**Issue by idb-** [nccgroup/house#3]
I may be an idiot (has happened before), but is there a way to launch app instead of attach using house? I need to perform hooks as soon as the app is loaded. Thanks in advance.

**Comment by iddoeldor** [comment]
https://github.com/iddoeldor/frida-snippets/blob/master/scripts/exec_shell_cmd.py

**Comment by idb-** [comment]
i meant from inside house. it seems as though house only attaches to running processes.

**Comment by H4oK3** [comment]
@idb- Yeah great question, I see your point, it shouldn't be hard to implement, I will find a time to work on it and push some updates with this feature;

**Comment by H4oK3** [comment]
@idb- Hey the updates have been pushed, now House will automatically spawn the app if it is not running, let me know if that helps.
