### ISSUE TITLE
python3.X is not support?

### ISSUE THREAD

**Issue by pharazone** [nccgroup/house#6]
hello.

I only have python3.X, so I run it, it cannot support python3.X.

**Comment by H4oK3** [comment]
Yes it does not support python 3.X; it's hard to support different python platforms, but there are a lot of stuff you can do if you do not want to conflict with your built-in python such as using virtualenv; etc.

**Comment by H4oK3** [comment]
Hey, just let you know that I pushed a bunch of updates earlier this week; and now it supports python3.
