### ISSUE TITLE
the frida require python3.x , and house is require python2.x

### ISSUE THREAD

**Issue by ldzSpace** [nccgroup/house#9]
Hi, I have one question is that   the frida require python3.x , and house is require python2.x ，
if i use python3.x ，and run  python3.x  app.py 8888 , an error appeared ,

File "app.py", line 127
    """
      ^
SyntaxError: invalid syntax

**Comment by H4oK3** [comment]
Hey, thanks for letting me know, I did not know Frida recommends using python 3; I will def. update House a little bit in the future to make it compatible with that. But at this point, Frida also runs well with python 2 as I am using it w/o issues; so I would suggest keep on it for now, also I would suggest using virtualenv for different python envs to get it work.

**Comment by H4oK3** [comment]
I am gonna close this for now as it is not a deadly issue at this point, but thanks for the feed back.
